// <auto-generated />
using CustomerCRUD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerCRUD.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20241029211612_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerCRUD.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Adress = "Zwyciestwa 13/5",
                            Budget = 60000,
                            Email = "AleksanderJaruga@gmail.com",
                            Name = "Aleksander Jaruga",
                            PhoneNumber = 638456736L
                        },
                        new
                        {
                            ID = 2,
                            Adress = "Al.Piastow 12/7",
                            Budget = 5000,
                            Email = "MichałZielony@gmail.com",
                            Name = "Michał Zielony",
                            PhoneNumber = 823462374L
                        },
                        new
                        {
                            ID = 3,
                            Adress = "Michałów 98/8",
                            Budget = 25000,
                            Email = "BartekLubelski@gmail.com",
                            Name = "Bartek Lubelski",
                            PhoneNumber = 837282737L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
